name: video_player_for_web_integration_tests
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3"

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface:
    git: https://github.com/kumsumit/video_player_platform_interface.git
  video_player_web:
    path: ../
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
